# Generated by Django 4.0.4 on 2022-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('current_location', models.CharField(blank=True, max_length=50, null=True)),
                ('from_destination', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
