# Generated by Django 4.0.4 on 2023-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_package_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='map_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2617.1432452717227!2d2.5469949679616315!3d49.00785970323614!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sparis%20airport!5e0!3m2!1sen!2sng!4v1677688572432!5m2!1sen!2sng', null=True),
        ),
    ]
